[package]
name = "rusty-snippets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skim = "0.9.4"
regex = "1.6.0"
clipboard = "0.5.0"

