set nocompatible

"set nowrap
set nowrap

set relativenumber
set ruler
set visualbell
set encoding=utf-8
set shiftwidth=4
set softtabstop=4
set expandtab

set backspace=2 " more powerful backspacing

nnoremap <SPACE> <Nop>
let mapleader = " "

" ===== adding indenting visual. Can turn on/off with leader - ig
set ts=4 sw=4 et
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1
let g:indent_guides_enable_on_vim_startup=1

" Yank to system clipboard
set clipboard=unnamed

" Faster copy to clipboard and pasting from clipboard
" Easiest way without extensions is by doing this
noremap <Leader>y "*y
noremap <Leader>p "*p
noremap <Leader>Y "+y
noremap <Leader>P "+p

" Move Line up/down in normal mode, insert mode, and visual mode using alt-j/k
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" Replace word under cursor globally
" nnoremap <Leader>a :%s/\<<C-r><C-w>\>/
nnoremap <Leader>a :%s/\<<C-r><C-w>\>//g<Left><Left>
" Replace word under cursor in line
nnoremap <Leader>s :s/\<<C-r><C-w>\>/


" http://vim.wikia.com/wiki/Change_cursor_shape_in_different_modes
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"


" When the page starts to scroll, keep the cursor 8 lines from the top and 8
" lines from the bottom
set scrolloff=8

" remap VIM 0 to first non-blank character
map 0 ^


" don't display welcome
set shortmess+=I

" Sets how many lines of history VIM has to remember
set history=700

"Always show current position
set ruler

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500


" Exit insert mode by typing kj rather than esc
" http://www.guyrutenberg.com/2013/09/23/quickly-exiting-insert-mode-in-vim/
:inoremap kk <ESC>
" exit even if capital if in caps lock
:inoremap KK <ESC>
