
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/jhendricks/.sdkman"
[[ -s "/Users/jhendricks/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/jhendricks/.sdkman/bin/sdkman-init.sh"
. "$HOME/.cargo/env"
